spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  session:
    timeout: 86400


hodolman:
  jwt-key : "kItB4fBY6rVkxV69VfrHdz/WpHiEVUVc2/8BPTEB3lA="

server:
  servlet:
    session:
      cookie:
        max-age: 172800