spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY} #?? ???? ?
      image:
        options:
          model: gpt-image-1-mini
          size: 1024x1024
          quality: low
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
jwt:
  issuer: cjfsud23@naver.com
  secret-key: study-test